---
# Configure secure

- name: service is enabled and started
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  become: true
  loop: "{{ secure_services_enable }}"
  when: secure_enable_service
