---
# Install secure packages

- name: unwanted packages are removed
  package:
    name: "{{ secure_packages_remove }}"
    state: absent
  become: true
  when: secure_remove_packages

- name: prereq repositories are installed
  package:
    name: "{{ secure_packages_repos }}"
    state: "{{ secure_packages_state }}"
  become: true

- name: prereq packages are installed
  package:
    name: "{{ secure_packages_prereq }}"
    state: "{{ secure_packages_state }}"
  become: true

- name: packages are installed
  package:
    name: "{{ secure_packages_install }}"
    state: "{{ secure_packages_state }}"
  become: true
